import {
	abc,
	abcAustralia,
	afp,
	aljazeera,
	arabNews,
	bbcNews,
	birminghamLive,
	bloomberg,
	bostonHerald,
	breitbart,
	buzzfeed,
	cbc,
	cbs,
	channel4,
	channel5,
	channelNewsAsia,
	cnbc,
	cnn,
	dailyMail,
	dailyRecord,
	democracyNow,
	denverPost,
	dw,
	eInternationalRelations,
	euronews,
	eveningStandard,
	express,
	firstPost,
	fox,
	france24,
	gbNews,
	globalIssues,
	globalNews,
	globeAndMail,
	guardian,
	heraldScotland,
	huffpost,
	ifpNews,
	independent,
	itv,
	japanTimes,
	laTimes,
	manchesterEveningNews,
	mercuryNews,
	metro,
	mirror,
	nbc,
	ndtv,
	news24,
	newYorkPost,
	newYorkTimes,
	northernIrelandWorld,
	npr,
	pbs,
	politico,
	politicsCoUk,
	proPublica,
	rawStory,
	reuters,
	rt,
	sabc,
	seatleTimes,
	skyNews,
	southChinaMorningPost,
	sputnik,
	straitsTimes,
	stv,
	sydneyMorningHerald,
	telegraph,
	theAmericanConservative,
	theAtlantic,
	theBulwark,
	theCipherBrief,
	theConversation,
	theDailyBeast,
	theDailyCaller,
	theDiplomat,
	theFederalist,
	theHill,
	theIntercept,
	theMoscowTimes,
	theNewHumanitarian,
	theNewYorker,
	theOnion,
	thePinkNews,
	theSun,
	theWorld,
	time,
	timesofindia,
	torontoStar,
	trt,
	un,
	usatoday,
	usNews,
	verge,
	vox,
	walesOnline,
	wallStreetJournal,
	washingtonPost,
	washingtonTimes,
	yahoo,
} from "./providers/providers";
export const NewsSources = {
	ARAB_NEWS: "Arab News",
	BBC: "BBC",
	GUARDIAN: "The Guardian",
	TELEGRAPH: "The Telegraph",
	MIRROR: "The Mirror",
	DAILY_MAIL: "The Daily Mail",
	METRO: "Metro",
	EVENING_STANDARD: "The Evening Standard",
	SUN: "The Sun",
	SKY: "Sky News",
	INDEPENDENT: "The Independent",
	HUFFPOST: "The Huffington Post",
	DAILY_RECORD: "The Daily Record",
	POLITICS_CO_UK: "politics.co.uk",
	THE_CONVERSATION: "The Conversation",
	MANCHESTER_EVENING_NEWS: "The Manchester Evening News",
	BIRMINGHAME_LIVE: "Birmingham Live",
	THE_PINK_NEWS: "The Pink News",
	NORTHERN_IRELAND_WORLD: "Northern Ireland World",
	WALES_ONLINE: "Wales Online",
	HERALD_SCOTLAND: "Herald Scotland",
	GB_NEWS: "GB News",

	CNN: "CNN",
	FOX: "Fox News",
	WALL_STREET_JOURNAL: "The Wall Street Journal",
	YAHOO: "Yahoo News",
	NPR: "NPR",
	WASHINGTON_TIMES: "Washington Times",
	LA_TIMES: "LA Times",
	MERCURY_NEWS: "Mercury News",
	CBS: "CBS",
	ABC: "ABC",
	BREITBART: "Breitbart",
	BOSTON_HEARLD: "Boston Herald",
	DENVER_POST: "Denver Post",
	NEW_YORK_POST: "New York Post",
	THE_HILL: "The Hill",
	POLITICO: "Politico",
	VOX: "Vox",
	BUZZFEED: "Buzzfeed",
	THE_ATLANTIC: "The Atlantic",
	SEATLE_TIMES: "Seattle Times",
	INTERCEPT: "The Intercept",
	VERGE: "The Verge",
	THE_DAILY_BEAST: "The Daily Beast",
	THE_NEW_YORKER: "The New Yorker",
	THE_ONION: "The Onion",
	THE_DAILY_CALLER: "The Daily Caller",
	THE_FEDERALIST: "The Federalist",
	THE_AMERICAN_CONSERVATIVE: "The American Conservative",
	THE_BULWARK: "The Bulwark",
	NEW_YORK_TIMES: "New York Times",

	AL_JAZEERA: "Al Jazeera",
	WASHINGTON_POST: "The Washington Post",
	CNBC: "CNBC",
	CBC: "CBC",
	DEUTSCHE_WELLE: "Deutsche Welle",
	FRANCE_24: "France 24",
	US_NEWS: "US News",
	GLOBAL_NEWS: "Global News",
	TIME: "Time",
	USA_TODAY: "USA Today",
	SYDNEY_MORNING_HERALD: "Sydney Morning Herald",
	GLOBE_AND_MAIL: "Globe and Mail",
	TORONTO_STAR: "Toronto Star",
	JAPAN_TIMES: "Japan Times",
	SOUTH_CHINA_MORNING_POST: "South China Morning Post",
	STRAITS_TIMES: "Straits Times",
	TIMES_OF_INDIA: "Times of India",
	RT: "RT",
	NDTV: "NDTV",
	E_INTERNATIONAL_RELATIONS: "E-International Relations",
	CIPHER_BRIEF: "The Cipher Brief",
	EXPRESS: "Daily Express",
	EURONEWS: "Euronews",
	CHANNEL_NEWS_ASIA: "Channel News Asia",
	NEWS_24: "News24",
	THE_DIPLOMAT: "The Diplomat",
	MOSCOW_TIMES: "The Moscow Times",
	THE_NEW_HUMANITARIAN: "The New Humanitarian",
	RAW_STORY: "Raw Story",
	IFP_NEWS: "IFP News",
	SCMP: "South China Morning Post",
	THE_WORLD: "The World",
	SPUTNIK: "Sputnik",
	AP: "Associated Press",
	GLOBAL_ISSUES: "Global Issues",
	UN: "United Nations",

	ITV: "ITV",
	CHANNEL_4: "Channel 4",
	CHANNEL_5: "Channel 5",
	STV: "STV",

	NBC: "NBC",
	PBS: "PBS",
	REUTERS: "Reuters",
	PRO_PUBLICA: "ProPublica",
	DEMOCRACY_NOW: "Democracy Now",
	BLOOMBERG: "Bloomberg",
	NINE_NEWS: "9News",
	ABC_AUSTRALIA: "ABC AUS",
	FIRST_POST: "First Post",
	AFP: "AFP",
	TRT: "TRT",
	SABC: "SABC",
} as const;

// We can type better
export const newsSourcesMap = new Map<string, any>([
	[NewsSources.ARAB_NEWS, arabNews],
	[NewsSources.BBC, bbcNews],
	[NewsSources.GUARDIAN, guardian],
	[NewsSources.TELEGRAPH, telegraph],
	[NewsSources.MIRROR, mirror],
	[NewsSources.DAILY_MAIL, dailyMail],
	[NewsSources.METRO, metro],
	[NewsSources.EVENING_STANDARD, eveningStandard],
	[NewsSources.SUN, theSun],
	[NewsSources.SKY, skyNews],
	[NewsSources.INDEPENDENT, independent],
	[NewsSources.HUFFPOST, huffpost],
	[NewsSources.DAILY_RECORD, dailyRecord],
	[NewsSources.POLITICS_CO_UK, politicsCoUk],
	[NewsSources.THE_CONVERSATION, theConversation],
	[NewsSources.MANCHESTER_EVENING_NEWS, manchesterEveningNews],
	[NewsSources.BIRMINGHAME_LIVE, birminghamLive],
	[NewsSources.THE_PINK_NEWS, thePinkNews],
	[NewsSources.NORTHERN_IRELAND_WORLD, northernIrelandWorld],
	[NewsSources.WALES_ONLINE, walesOnline],
	[NewsSources.HERALD_SCOTLAND, heraldScotland],
	[NewsSources.GB_NEWS, gbNews],
	[NewsSources.CNN, cnn],
	[NewsSources.FOX, fox],
	[NewsSources.WALL_STREET_JOURNAL, wallStreetJournal],
	[NewsSources.YAHOO, yahoo],
	[NewsSources.NPR, npr],
	[NewsSources.WASHINGTON_TIMES, washingtonTimes],
	[NewsSources.LA_TIMES, laTimes],
	[NewsSources.MERCURY_NEWS, mercuryNews],
	[NewsSources.CBS, cbs],
	[NewsSources.ABC, abc],
	[NewsSources.BREITBART, breitbart],
	[NewsSources.BOSTON_HEARLD, bostonHerald],
	[NewsSources.DENVER_POST, denverPost],
	[NewsSources.NEW_YORK_POST, newYorkPost],
	[NewsSources.THE_HILL, theHill],
	[NewsSources.POLITICO, politico],
	[NewsSources.VOX, vox],
	[NewsSources.BUZZFEED, buzzfeed],
	[NewsSources.THE_ATLANTIC, theAtlantic],
	[NewsSources.SEATLE_TIMES, seatleTimes],
	[NewsSources.INTERCEPT, theIntercept],
	[NewsSources.VERGE, verge],
	[NewsSources.THE_DAILY_BEAST, theDailyBeast],
	[NewsSources.THE_NEW_YORKER, theNewYorker],
	[NewsSources.THE_ONION, theOnion],
	[NewsSources.THE_DAILY_CALLER, theDailyCaller],
	[NewsSources.THE_FEDERALIST, theFederalist],
	[NewsSources.THE_AMERICAN_CONSERVATIVE, theAmericanConservative],
	[NewsSources.THE_BULWARK, theBulwark],
	[NewsSources.NEW_YORK_TIMES, newYorkTimes],
	[NewsSources.AL_JAZEERA, aljazeera],
	[NewsSources.WASHINGTON_POST, washingtonPost],
	[NewsSources.CNBC, cnbc],
	[NewsSources.CBC, cbc],
	[NewsSources.DEUTSCHE_WELLE, dw],
	[NewsSources.FRANCE_24, france24],
	[NewsSources.US_NEWS, usNews],
	[NewsSources.GLOBAL_NEWS, globalNews],
	[NewsSources.TIME, time],
	[NewsSources.USA_TODAY, usatoday],
	[NewsSources.SYDNEY_MORNING_HERALD, sydneyMorningHerald],
	[NewsSources.GLOBE_AND_MAIL, globeAndMail],
	[NewsSources.TORONTO_STAR, torontoStar],
	[NewsSources.JAPAN_TIMES, japanTimes],
	[NewsSources.SOUTH_CHINA_MORNING_POST, southChinaMorningPost],
	[NewsSources.STRAITS_TIMES, straitsTimes],
	[NewsSources.TIMES_OF_INDIA, timesofindia],
	[NewsSources.RT, rt],
	[NewsSources.NDTV, ndtv],
	[NewsSources.E_INTERNATIONAL_RELATIONS, eInternationalRelations],
	[NewsSources.CIPHER_BRIEF, theCipherBrief],
	[NewsSources.EXPRESS, express],
	[NewsSources.EURONEWS, euronews],
	[NewsSources.CHANNEL_NEWS_ASIA, channelNewsAsia],
	[NewsSources.NEWS_24, news24],
	[NewsSources.THE_DIPLOMAT, theDiplomat],
	[NewsSources.MOSCOW_TIMES, theMoscowTimes],
	[NewsSources.THE_NEW_HUMANITARIAN, theNewHumanitarian],
	[NewsSources.RAW_STORY, rawStory],
	[NewsSources.IFP_NEWS, ifpNews],
	[NewsSources.SCMP, southChinaMorningPost],
	[NewsSources.THE_WORLD, theWorld],
	[NewsSources.SPUTNIK, sputnik],
	[NewsSources.GLOBAL_ISSUES, globalIssues],
	[NewsSources.UN, un],
	[NewsSources.ITV, itv],
	[NewsSources.CHANNEL_4, channel4],
	[NewsSources.CHANNEL_5, channel5],
	[NewsSources.STV, stv],
	[NewsSources.NBC, nbc],
	[NewsSources.PBS, pbs],
	[NewsSources.REUTERS, reuters],
	[NewsSources.PRO_PUBLICA, proPublica],
	[NewsSources.DEMOCRACY_NOW, democracyNow],
	[NewsSources.BLOOMBERG, bloomberg],
	[NewsSources.NINE_NEWS, nbc],

	[NewsSources.ABC_AUSTRALIA, abcAustralia],
	[NewsSources.FIRST_POST, firstPost],
	[NewsSources.AFP, afp],
	[NewsSources.TRT, trt],
	[NewsSources.SABC, sabc],
]);
