import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { MainHeader } from "../components/header/main-header";
import AuthProvider from "@/components/header/auth/auth-provider";
import { connectToMongoDB } from "@/lib/mongo/db";
import { MainFooter } from "@/components/footer/main-footer";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	// TODO:
	// Initialize services / we need to guarantee server use only
	// Create a Providers component to match accepted standard
	connectToMongoDB();
	return (
		<html lang="en">
			<AuthProvider>
				<body className={`${geistSans.variable} ${geistMono.variable}`}>
					<MainHeader />
					{children}
					<MainFooter />
				</body>
			</AuthProvider>
		</html>
	);
}
