import { MainHeader } from "@/components/header/main-header";
import { PageLayout } from "@/components/ui/layout/page-layout";
import { Metadata } from "next";

export const metadata: Metadata = {
	title: "Datatattat",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
	params: Promise<{ route: string[] }>;
}>) {
	return (
		<PageLayout>
			<MainHeader />
			{children}
		</PageLayout>
	);
}
